name: ChatTutor

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies 
      run: pip install -r requirements.txt      
    - name: Set python path
      run: |
        export PYTHONPATH=$(pwd)/ChatTutor
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV        
    - name: Test with pytest
      run: |
        cd ChatTutor
        pytest -v -s